# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/72433cfb-eb42-42da-9838-c9432399a1ce";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5737970a-a68a-4068-b8da-dff32732dd4e".device = "/dev/disk/by-uuid/5737970a-a68a-4068-b8da-dff32732dd4e";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/0E82-52B5";
      fsType = "vfat";
    };

  fileSystems."/old-ubuntu" =
    { device = "/dev/disk/by-uuid/0ccbbaaf-ca43-44c5-8ec9-8f239d259f04";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bd74357d-90fa-41b8-9c15-3e1104a8a943"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
